### ISSUE TITLE
Modifications dans la bdd

### ISSUE THREAD

**Issue by ghost** [renoted/Gameloc#1]
Modifications à faire dans la bdd : 
- changer "adress" en "address"

**Comment by RomainTreppoz** [comment]
Une réponse via messagerie, ça donnerait quoi ?

Romain T

De : ducreuxr [mailto:notifications@github.com] 
Envoyé : mardi 12 janvier 2016 09:43
À : renoted/Gameloc
Cc : RomainTreppoz
Objet : Re: [Gameloc] Modifications dans la bdd (#1)

Closed #1 https://github.com/renoted/Gameloc/issues/1 .
